//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniqueDistance.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniqueDistance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must pass 1 argument: the board size..
        /// </summary>
        internal static string ConsoleMessage_MissingSize {
            get {
                return ResourceManager.GetString("ConsoleMessage_MissingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} =&gt; {1} solution(s):.
        /// </summary>
        internal static string ConsoleMessageFormat_SolutionsPerSize {
            get {
                return ResourceManager.GetString("ConsoleMessageFormat_SolutionsPerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array dimensions exceeded supported range..
        /// </summary>
        internal static string ExceptionMessage_ArrayTooSmallOrTooLarge {
            get {
                return ResourceManager.GetString("ExceptionMessage_ArrayTooSmallOrTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration already finished..
        /// </summary>
        internal static string ExceptionMessage_EnumerationFinished {
            get {
                return ResourceManager.GetString("ExceptionMessage_EnumerationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has not started. Call MoveNext..
        /// </summary>
        internal static string ExceptionMessage_EnumerationNotStarted {
            get {
                return ResourceManager.GetString("ExceptionMessage_EnumerationNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max must be must be large enough such that the range is larger than the size..
        /// </summary>
        internal static string ExceptionMessage_MaxTooSmall {
            get {
                return ResourceManager.GetString("ExceptionMessage_MaxTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a non-negative integer..
        /// </summary>
        internal static string ExceptionMessage_ValueIsNegative {
            get {
                return ResourceManager.GetString("ExceptionMessage_ValueIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown translation: {0}..
        /// </summary>
        internal static string ExceptionMessageFormat_UnknownTranslation {
            get {
                return ResourceManager.GetString("ExceptionMessageFormat_UnknownTranslation", resourceCulture);
            }
        }
    }
}
